namespace:
  name: demo
 
service:
  port: 8111
  type: ClusterIP

image:
  repository: python-helloworld
  tag: 1.17.1
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 50m
    memory: 256Mi

configmap:
  data: "version: 1.17.1"
